#!/bin/bash
int_ip=$(hostname -i)
ext_ip=$(curl ifconfig.me)

sed -i "s/listening-ip=.*/listening-ip=${int_ip}/" turnserver.conf
sed -i "s/relay-ip=.*/relay-ip=${ext_ip}/" turnserver.conf
sed -i "s/external-ip=.*/external-ip=${ext_ip}\/${int_ip}/" turnserver.conf

sudo cp turnserver.conf /usr/local/etc/turnserver.conf